core/models/__init__.py
from .admin import User
from .products import Product

core/models/admin.py
from ..extensions import db
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True, default='admin')
    password = db.Column(db.Text)

    def __repr__(self):
        return '<User %r>' % self.username
    
    def check_password(self, input_password):
        return check_password_hash(self.password, input_password)
    
    def set_password(self, password):
        self.password = generate_password_hash(password)
        db.session.commit()
        return self.password

core/models/products.py
from ..extensions import db
from datetime import datetime

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    price = db.Column(db.Float, nullable=False)
    price_id = db.Column(db.String(50), nullable=False, unique=True)
    description = db.Column(db.Text, nullable=False)
    image_url = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

core/__init__.py
from flask import Flask, render_template, request
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_mail import Message

import stripe

import os

from .extensions import db, migrate, login_manager, mail
from dotenv import find_dotenv, load_dotenv
from .models import User, Product

load_dotenv(find_dotenv())

def create_app():
    app = Flask(__name__)
    # App Config
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DB_URI')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')

    # mail config
    app.config['MAIL_SERVER']='sandbox.smtp.mailtrap.io'
    app.config['MAIL_PORT'] = 2525
    app.config['MAIL_USERNAME'] = os.environ.get('MAIL_USERNAME')
    app.config['MAIL_PASSWORD'] = os.environ.get('MAIL_PASSWORD')
    app.config['MAIL_USE_TLS'] = True
    app.config['MAIL_USE_SSL'] = False
    
    # initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    admin = Admin(app)

    stripe.api_key = os.environ.get('STRIPE_API_KEY')

    # stripe session routes
    @app.route('/order-success/', methods=['GET'])
    def order_success():
        session_id = request.args.get('session_id')

        session = stripe.checkout.Session.retrieve(session_id)
        customer_email = session.customer_details.email
        customer_name = session.customer_details.name

        email = customer_email if customer_email else "Unknown"
        name = customer_name if customer_name else "Unknown"

        msg = Message(
            'Order Confirmation',
            sender='admin@store.com',
            recipients=[email]
        )
        msg.body=f'Thanks for your order {name}'
        mail.send(msg)
        print('message sent')
        print(session)
        
        context = {
            'name': name,
            'title': 'Order Successful'
        }

        return render_template(
            'stripe/success.html',
            **context
        )

    @app.route('/order-cancelled/', methods=['GET'])
    def order_cancelled():
        return 'order cancelled'

    # flask admin
    admin.add_view(ModelView(User, db.session))
    admin.add_view(ModelView(Product, db.session))

    # flask login setup
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'

    from .models import admin

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # register blueprints
    from .routes import main_bp, product_bp, auth_bp
    app.register_blueprint(main_bp)
    app.register_blueprint(product_bp)
    app.register_blueprint(auth_bp)

    print(f'App: {app} running')

    return app

core/routes/__init__.py
from .main import main as main_bp
from .products import products as product_bp
from .auth import auth as auth_bp

core/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user
from ..models import User
from werkzeug.security import check_password_hash

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        print(user.username)
        print(check_password_hash(user.password, password))

        if user and check_password_hash(user.password, password):
            login_user(user)
            print('logged in')
            return redirect(url_for('main.index'))
        else:
            print('login failed')
            return redirect(url_for('auth.login'))
    
    context = {
        'title': 'Login | Store Name',
    }

    return render_template(
        'auth/login.html',
        **context
    )

@auth.route('/logout/', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/change-password/', methods=['GET'])
def register():
    return 'change password'

core/routes/main.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__, url_prefix='/')

@main.route('/', methods=['GET'])
def index():
    return render_template('index.html')

core/routes/products.py
from flask import Blueprint, render_template, request, flash, redirect
from ..models import Product
import os
import stripe

products = Blueprint('products', __name__, url_prefix='/products')

@products.route('/', methods=['GET'])
def get_all_products():
    sort = request.args.get('sort')

    context = {
        'title': 'Products | Store Name',
        'products': Product.query
        .order_by(sort)
        .all()
    }

    return render_template(
        'products/products.html',
        **context
        )

@products.route('/<int:product_id>/', methods=['GET'])
def get_single_product(product_id):
    product = Product.query.get(product_id)
    context = {
        'title': product.name,
        'product': product
    }
    return render_template(
        'products/product_page.html',
        **context
        )

DOMAIN = 'http://127.0.0.1:5000/'

stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')

@products.route('/<int:id>/create-checkout-session/', methods=['GET', 'POST'])
def create_checkout_session(id):
    product = Product.query.filter_by(id=id).first()
    price_id = product.price_id

    try:
        checkout_session = stripe.checkout.Session.create(
            submit_type='pay',
            billing_address_collection='auto',
            shipping_address_collection={
                'allowed_countries': ['GB']
            },
            line_items=[
                {
                    'price': price_id,
                    'quantity': 1,
                },
            ],
            mode='payment',
            success_url=DOMAIN + 'order-success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=DOMAIN + 'order-cancelled/',
        )
    except Exception as e:
        return str(e)
    flash('Purchase Successful!', 'success')
    return redirect(
        checkout_session.url,
        code=303
    )

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#32025A"/>
    <meta name="description" content="Join the brotherhood! With Brotherhood Records you can not only buy records to add to your collection, but also keep track and share your favourite music">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>
        {{title}}
    </title>
</head>
<body>
    {% include 'components/header.html' %}
    <!-- flashed messages -->
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    

    {% block content %}

    {% endblock %}

    {% include 'components/footer.html' %}

    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

core/templates/components/footer.html
<footer class="footer__wrapper">
    <p class="footer__content">
        Created by &copy; Josh Shepherd 2023
    </p>
</footer>

core/templates/components/header.html
<header class="header__wrapper">
    <section class="header__logo">
        <h1>Store Name</h1>
    </section>
    <nav class="nav__wrapper">
        <ul class="nav__items">
            <li class="nav__item">
                <a href="" 
                class="nav__item-link">
                    Home
                </a>
            </li>
            <li class="nav__item">
                <a href="{{url_for('products.get_all_products')}}" 
                class="nav__item-link">
                    Products
                </a>
            </li>
        </ul>
    </nav>
    <img src="{{url_for('static', filename='icons/bars-solid.svg')}}" 
    alt="Menu" 
    class="mobile__nav-svg"
    id="mobileNavBtn">
</header>
<nav class="mobile__nav-wrapper">
    <ul class="mobile__nav" id="mobileNav">
        {% if current_user.is_authenticated %}
        <li class="mobile__nav-item mobile__nav-greeting">
            Hello, {{current_user.name}}
        </li>
        {% endif %}
        <a href="{{url_for('products.get_all_products')}}" class="mobile__nav-link">
        <li class="mobile__nav-item"> 
                Home
        </li>
        </a>
        <a href="{{url_for('products.get_all_products')}}" class="mobile__nav-link">
        <li class="mobile__nav-item"> 
                Products
        </li>
        </a>
    </ul>
</nav>

core/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

core/templates/products/product_page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="product__page-wrapper">
            <div class="product__page-main">
                <div class="product__page-img-wrapper">
                    <img src="{{product.image_url}}" 
                    alt="{{product.name}}" 
                    class="product__page-img"
                    loading="lazy">
                </div>
                <div class="product_details">
                        <p>{{product.name}}</p>
                        <p>£{{product.price}}</p>
                        <p>{{product.description}}</p>
                </div>
            </div>
            <div class="product__page-buy">
                <div class="buy_now">
                    <form action="{{url_for('products.create_checkout_session', id=product.id)}}" method="post" class="buy_form">
                        <input type="submit" value="Buy Now!" class="buy_btn">
                    </form>
                </div>
            </div>
        </div>
    </div>
        
{% endblock %}

core/templates/products/products.html
{% extends 'base.html' %}

{% block content %}
    <main class="container">
        <div class="genre__search-wrapper">
            <div class="genre__search-title">
                <h2>
                    Products
                </h2>
            </div>
            <!-- <div class="category__search-links">
                {% for category in categories %}
                <a href="{{url_for('product.product_by_category', category=category)}}" class="genre__search-link">{{genre}}</a>
                {% endfor %}
            </div> -->
        </div>
        <div class="sort__form-wrapper">
            <form action="" method="GET" class="sort__form">
                <select name="sort" id="sort" title="Sort Products">
                    <option value="name">Name</option>
                    <option value="price">Price</option>
                </select>
                <input type="submit" value="Sort Products">
            </form>
        </div>
        
        {% for product in products  %}
        <div class="product_wrapper slider">
            <div class="product__img-wrapper">
                <img src="{{product.image_url}}" 
                alt="{{product.name}}" 
                class="product__img"
                loading="lazy">
            </div>
            <div class="product_details">
                    <p><strong>{{product.name}}</strong></p>
                    <p>£{{product.price}}</p>
                    <p>{{product.description}}</p>
            </div>
            <div class="product__ctas">
                <div class="product_link">
                    <a href="{{url_for('products.get_single_product', product_id=product.id)}}">
                        View More
                    </a>
                </div>
            </div>
        </div>
        </div>
            {% endfor %}
    </main>
{% endblock %}

core/templates/stripe/success.html
{% extends 'base.html' %}
{% block content %}

<div class="container container__secondary">
    <p class="paragraph__content">
        Thank you for your order, {{  name  }}.
    </p>
    <p>
        Your order will arrive in 5-7 working days
    </p>
</div>

{% endblock %}